version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'routebots'
      MYSQL_ROOT_PASSWORD: 'Abc554041' # Usa MYSQL_ROOT_PASSWORD para la contraseña de root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3307"
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data:

